window.CHLOE_PORTFOLIO = {
  email: "hello@chloe.studio",
  translations: {
    vi: {
      "meta.title": "CHLOE — Kết nối những điều tử tế",
      "accessibility.skip": "Đi tới nội dung",
      "accessibility.menu": "Mở menu",
      "brand.issue": "Organic sales · Hồ sơ cá nhân",
      "nav.approach": "Cách tôi làm việc",
      "nav.organic": "Organic",
      "nav.journey": "Những chuyến đi",
      "nav.about": "Về Chloe",
      "nav.contact": "Liên hệ",
      "hero.role": "Sales thực phẩm organic · Xây dựng quan hệ",
      "hero.eyebrow": "Một cách làm sales dịu dàng và có chiều sâu",
      "hero.lineOne": "Bán bằng sự",
      "hero.lineTwo": "thấu hiểu.",
      "hero.intro":
        "Chloe kết nối thực phẩm organic tử tế với đúng người — bằng sự lắng nghe, kiến thức sản phẩm và những mối quan hệ được nuôi dưỡng lâu dài.",
      "hero.ctaWork": "Hiểu cách Chloe làm việc",
      "hero.ctaContact": "Bắt đầu một cuộc trò chuyện",
      "hero.imageAlt": "Chloe trong một khoảnh khắc yên tĩnh bên bàn làm việc",
      "hero.captionOne": "Một người quan sát trước khi lên tiếng",
      "hero.captionTwo": "Ghi chép riêng / 01",
      "hero.qualityOne": "Lắng nghe kỹ",
      "hero.qualityTwo": "Hiểu sản phẩm",
      "hero.qualityThree": "Xây niềm tin",
      "manifesto.label": "Quan điểm",
      "manifesto.title": "Không cần nói thật nhiều để tạo nên một kết nối thật.",
      "manifesto.lead":
        "Chloe sống khá khép kín, nhưng trong công việc lại dành rất nhiều sự chú ý cho con người: điều họ cần, điều họ chưa nói và điều khiến họ thật sự tin tưởng.",
      "manifesto.body":
        "Với cô, sales không phải là thuyết phục bằng mọi giá. Đó là tìm đúng sản phẩm, đúng câu chuyện và đúng thời điểm để một lựa chọn tốt trở nên tự nhiên.",
      "approach.label": "Cách làm việc",
      "approach.eyebrow": "Sales đặt mối quan hệ làm trung tâm",
      "approach.title": "Ít áp lực hơn. Nhiều thấu hiểu hơn.",
      "approach.intro":
        "Một cách tiếp cận sales bình tĩnh, có chuẩn bị và đặt mối quan hệ dài hạn ở trung tâm.",
      "approach.one.title": "Lắng nghe trước khi đề xuất",
      "approach.one.body":
        "Hiểu nhu cầu thật, bối cảnh kinh doanh và những khoảng trống chưa được gọi tên trước khi nói về sản phẩm.",
      "approach.two.title": "Kể đúng giá trị organic",
      "approach.two.body":
        "Chuyển nguồn gốc, quy trình và chất lượng thành một câu chuyện rõ ràng, gần gũi và đủ đáng tin để khách hàng lựa chọn.",
      "approach.three.title": "Chăm một mối quan hệ dài lâu",
      "approach.three.body":
        "Theo sát sau mỗi cuộc trao đổi, giữ lời và để sự tử tế nhất quán trở thành lý do người khác muốn đồng hành.",
      "organic.label": "Organic",
      "organic.eyebrow": "Từ nguồn gốc đến niềm tin",
      "organic.title": "Điều tốt lành cần được kể một cách thật lòng.",
      "organic.body":
        "Thực phẩm organic không chỉ là một nhãn dán. Đằng sau đó là đất, người trồng, tiêu chuẩn và những lựa chọn có trách nhiệm. Công việc của Chloe là giúp giá trị ấy đi trọn đường đến người mua.",
      "organic.one.kicker": "Hiểu nguồn gốc",
      "organic.one.title": "Hiểu nơi sản phẩm bắt đầu",
      "organic.one.body": "Nguồn gốc, con người, quy trình và tiêu chuẩn tạo nên chất lượng.",
      "organic.two.kicker": "Diễn giải giá trị",
      "organic.two.title": "Biến giá trị thành điều dễ hiểu",
      "organic.two.body": "Nói đúng điều người mua quan tâm, không tô vẽ và không làm quá.",
      "organic.three.kicker": "Xây niềm tin",
      "organic.three.title": "Để niềm tin dẫn tới lựa chọn",
      "organic.three.body":
        "Một quyết định bền vững bắt đầu từ thông tin rõ ràng và cảm giác an tâm.",
      "organic.four.kicker": "Cùng phát triển",
      "organic.four.title": "Cùng nhau nuôi dưỡng tăng trưởng",
      "organic.four.body":
        "Theo dõi, phản hồi và phát triển quan hệ sau điểm bán đầu tiên.",
      "journey.imageAlt": "Chloe lặng lẽ xem một cuốn sách trong chuyến đi",
      "journey.captionOne": "Đi để nhìn thế giới chậm hơn",
      "journey.label": "Những chuyến đi",
      "journey.eyebrow": "Đi xa, hiểu gần",
      "journey.title": "Đi xa để hiểu con người gần hơn.",
      "journey.lead":
        "Chloe thích những chuyến đi không quá vội — nơi có thể quan sát cách người ta ăn, sống, chọn một món đồ và dành thời gian cho nhau.",
      "journey.quote":
        "“Mỗi nơi đều có một nhịp riêng. Chỉ khi chậm lại, mình mới thật sự nghe thấy.”",
      "journey.noteOne": "Chợ địa phương",
      "journey.noteTwo": "Quán cà phê yên tĩnh",
      "journey.noteThree": "Những cung đường dài",
      "journey.noteFour": "Bữa ăn có câu chuyện",
      "about.label": "Về Chloe",
      "about.lineOne": "Kín đáo theo bản tính.",
      "about.lineTwo": "Chú tâm bởi lựa chọn.",
      "about.bodyOne":
        "Sinh ngày 14 tháng 11 năm 2000, Chloe là một người hướng nội, yêu khoảng riêng và thường tìm thấy năng lượng trong những điều giản dị.",
      "about.bodyTwo":
        "Sự yên lặng giúp cô quan sát tinh hơn; công việc sales giúp cô bước ra khỏi thế giới riêng để tạo nên những kết nối có ý nghĩa. Organic food là điểm gặp gỡ tự nhiên giữa nghề nghiệp và niềm tin vào một lối sống tốt lành hơn.",
      "about.factOne.label": "Bản tính",
      "about.factOne.value": "Người quan sát yên lặng",
      "about.factTwo.label": "Công việc",
      "about.factTwo.value": "Sales thực phẩm organic",
      "about.factThree.label": "Cách kết nối",
      "about.factThree.value": "Lắng nghe rồi mới nói",
      "about.factFour.label": "Ngoài công việc",
      "about.factFour.value": "Du lịch & góc nhỏ yên tĩnh",
      "notes.label": "Ghi chép riêng",
      "notes.title": "Những điều nhỏ nói lên một con người.",
      "notes.one.title": "Sự chân thành không cần âm lượng",
      "notes.one.body":
        "Một cuộc trò chuyện tốt không nằm ở việc nói bao nhiêu, mà ở cảm giác người đối diện thật sự được lắng nghe.",
      "notes.two.title": "Một sản phẩm tốt nên có nguồn gốc rõ ràng",
      "notes.two.body":
        "Khi hiểu nó đến từ đâu và được làm như thế nào, việc giới thiệu sản phẩm trở nên tự nhiên hơn rất nhiều.",
      "notes.three.title": "Đi xa không phải để chạy trốn",
      "notes.three.body":
        "Đó là cách đổi góc nhìn, nhìn lại chính mình và mang về những câu chuyện đáng nhớ.",
      "contact.label": "Liên hệ",
      "contact.kicker": "Một cuộc trò chuyện vừa đủ",
      "contact.lineOne": "Hãy bắt đầu bằng",
      "contact.lineTwo": "một lời chào.",
      "contact.body":
        "Nếu bạn đang tìm một người đồng hành sales cho sản phẩm organic, muốn trao đổi về cơ hội hợp tác hoặc đơn giản là có một câu chuyện hay — Chloe luôn sẵn lòng lắng nghe.",
      "contact.email": "Viết email cho Chloe",
      "contact.copy": "Sao chép email",
      "contact.availability": "Sẵn sàng cho những cơ hội phù hợp · GMT+7",
      "contact.form.name": "Tên của bạn",
      "contact.form.namePlaceholder": "Chloe nên gọi bạn thế nào?",
      "contact.form.email": "Địa chỉ email",
      "contact.form.emailPlaceholder": "ban@example.com",
      "contact.form.subject": "Chủ đề",
      "contact.form.subjectPlaceholder": "Organic, sales, hợp tác…",
      "contact.form.message": "Lời nhắn",
      "contact.form.messagePlaceholder": "Hãy kể Chloe nghe một chút…",
      "contact.form.submit": "Gửi lời nhắn",
      "contact.form.sending": "Đang gửi…",
      "contact.form.success": "Cảm ơn bạn — Chloe đã nhận được lời nhắn.",
      "contact.form.error": "Chưa thể gửi lời nhắn. Vui lòng thử lại hoặc dùng email.",
      "footer.line": "Organic food sales · Lặng lẽ kết nối những điều tử tế.",
      "footer.back": "Về đầu trang",
      "toast.copied": "Đã sao chép email",
    },
    en: {
      "meta.title": "CHLOE — Quietly connecting good things",
      "accessibility.skip": "Skip to content",
      "accessibility.menu": "Open menu",
      "brand.issue": "Organic sales · Personal folio",
      "nav.approach": "My approach",
      "nav.organic": "Organic",
      "nav.journey": "Journeys",
      "nav.about": "About Chloe",
      "nav.contact": "Contact",
      "hero.role": "Organic food sales · Relationship builder",
      "hero.eyebrow": "A softer, more thoughtful way to sell",
      "hero.lineOne": "Selling through",
      "hero.lineTwo": "understanding.",
      "hero.intro":
        "Chloe connects thoughtful organic food with the right people — through attentive listening, product understanding and relationships made to last.",
      "hero.ctaWork": "Discover Chloe’s approach",
      "hero.ctaContact": "Start a conversation",
      "hero.imageAlt": "Chloe in a quiet moment at her work table",
      "hero.captionOne": "An observer before a speaker",
      "hero.captionTwo": "Private notes / 01",
      "hero.qualityOne": "Listen closely",
      "hero.qualityTwo": "Know the product",
      "hero.qualityThree": "Earn the trust",
      "manifesto.label": "Point of view",
      "manifesto.title": "You do not have to say much to make a real connection.",
      "manifesto.lead":
        "Reserved by nature, Chloe gives people her full attention at work: what they need, what they have not said and what helps them genuinely trust.",
      "manifesto.body":
        "To her, sales is never persuasion at any cost. It is finding the right product, the right story and the right moment for a good choice to feel natural.",
      "approach.label": "My approach",
      "approach.eyebrow": "Relationship-led sales",
      "approach.title": "Less pressure. More understanding.",
      "approach.intro":
        "A calm, prepared approach to sales that keeps the long-term relationship at its centre.",
      "approach.one.title": "Listen before offering",
      "approach.one.body":
        "Understand the real need, the business context and the gaps left unsaid before talking about a product.",
      "approach.two.title": "Tell the organic value clearly",
      "approach.two.body":
        "Turn origin, process and quality into a story that is clear, human and trustworthy enough to choose.",
      "approach.three.title": "Care for the long relationship",
      "approach.three.body":
        "Follow through after every conversation, keep promises and let consistent care become the reason people stay.",
      "organic.label": "Organic",
      "organic.eyebrow": "From origin to trust",
      "organic.title": "Good things deserve to be told honestly.",
      "organic.body":
        "Organic food is more than a label. Behind it are soil, growers, standards and responsible choices. Chloe’s work is to help that value travel all the way to the buyer.",
      "organic.one.kicker": "Know the source",
      "organic.one.title": "Understand where it begins",
      "organic.one.body": "Origin, people, process and standards are what create quality.",
      "organic.two.kicker": "Translate the value",
      "organic.two.title": "Make the value easy to understand",
      "organic.two.body": "Speak to what buyers care about, without overclaiming or overselling.",
      "organic.three.kicker": "Earn the trust",
      "organic.three.title": "Let trust lead to the choice",
      "organic.three.body": "A lasting decision begins with clear information and peace of mind.",
      "organic.four.kicker": "Grow together",
      "organic.four.title": "Nurture growth together",
      "organic.four.body": "Follow up, listen and develop the relationship beyond the first sale.",
      "journey.imageAlt": "Chloe quietly looking through a book while travelling",
      "journey.captionOne": "Travelling to see the world more slowly",
      "journey.label": "Journeys",
      "journey.eyebrow": "Away, but closer",
      "journey.title": "Going farther to understand people better.",
      "journey.lead":
        "Chloe is drawn to unhurried journeys — places where she can notice how people eat, live, choose an object and make time for one another.",
      "journey.quote":
        "“Every place has its own rhythm. Only when I slow down can I truly hear it.”",
      "journey.noteOne": "Local markets",
      "journey.noteTwo": "Quiet cafés",
      "journey.noteThree": "Long roads",
      "journey.noteFour": "Meals with a story",
      "about.label": "About Chloe",
      "about.lineOne": "Reserved by nature.",
      "about.lineTwo": "Attentive by choice.",
      "about.bodyOne":
        "Born on 14 November 2000, Chloe is an introvert who values privacy and often finds energy in simple, quiet things.",
      "about.bodyTwo":
        "Stillness helps her observe more closely; sales invites her beyond her inner world to create meaningful connections. Organic food is the natural meeting point between her work and her belief in a kinder way of living.",
      "about.factOne.label": "Nature",
      "about.factOne.value": "Quiet observer",
      "about.factTwo.label": "Work",
      "about.factTwo.value": "Organic food sales",
      "about.factThree.label": "Connection",
      "about.factThree.value": "Listen, then speak",
      "about.factFour.label": "Beyond work",
      "about.factFour.value": "Travel & quiet corners",
      "notes.label": "Private notes",
      "notes.title": "Small things that say something true.",
      "notes.one.title": "Sincerity does not need volume",
      "notes.one.body":
        "A good conversation is not measured by how much is said, but by whether the other person feels truly heard.",
      "notes.two.title": "A good product should have a clear origin",
      "notes.two.body":
        "When you understand where it comes from and how it is made, introducing it feels much more natural.",
      "notes.three.title": "Going away is not running away",
      "notes.three.body":
        "It is a way to change perspective, meet yourself again and bring home stories worth keeping.",
      "contact.label": "Contact",
      "contact.kicker": "A conversation, just enough",
      "contact.lineOne": "Let’s begin with",
      "contact.lineTwo": "a simple hello.",
      "contact.body":
        "If you are looking for a thoughtful sales partner for an organic product, want to discuss an opportunity or simply have a good story to share — Chloe is always willing to listen.",
      "contact.email": "Write to Chloe",
      "contact.copy": "Copy email",
      "contact.availability": "Open to thoughtful opportunities · GMT+7",
      "contact.form.name": "Your name",
      "contact.form.namePlaceholder": "How should Chloe call you?",
      "contact.form.email": "Email address",
      "contact.form.emailPlaceholder": "you@example.com",
      "contact.form.subject": "Subject",
      "contact.form.subjectPlaceholder": "Organic, sales, collaboration…",
      "contact.form.message": "Your note",
      "contact.form.messagePlaceholder": "Tell Chloe a little more…",
      "contact.form.submit": "Send a note",
      "contact.form.sending": "Sending…",
      "contact.form.success": "Thank you — your note has reached Chloe.",
      "contact.form.error": "The note could not be sent. Please try again or use email.",
      "footer.line": "Organic food sales · Quietly connecting good things.",
      "footer.back": "Back to top",
      "toast.copied": "Email copied",
    },
  },
};
